package org.booklore.service.kobo;

import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.apache.commons.lang3.StringUtils;
import org.booklore.config.security.service.AuthenticationService;
import org.booklore.model.dto.BookLoreUser;
import org.booklore.model.dto.kobo.KoboEventsContainer;
import org.booklore.model.dto.request.ReadingSessionRequest;
import org.booklore.model.entity.BookEntity;
import org.booklore.model.entity.BookMetadataEntity;
import org.booklore.model.entity.ReadingSessionEntity;
import org.booklore.model.enums.BookFileType;
import org.booklore.repository.BookMetadataRepository;
import org.booklore.repository.BookRepository;
import org.booklore.repository.ReadingSessionRepository;
import org.booklore.service.ReadingSessionService;
import org.booklore.service.book.BookUpdateService;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Service
@RequiredArgsConstructor
public class KoboEventsService {
    private static final String MONETIZATION_TYPE_PAID = "Paid";
    private static final String MONETIZATION_TYPE_SIDELOADED = "Sideloaded";
    private static final String EVENT_TYPE_OPEN_CONTENT = "OpenContent";
    private static final String EVENT_TYPE_LEAVE_CONTENT = "LeaveContent";

    private final AuthenticationService authenticationService;
    private final ReadingSessionService readingSessionService;
    private final BookRepository bookRepository;
    private final BookMetadataRepository bookMetadataRepository;
    private final ReadingSessionRepository readingSessionRepository;
    private final BookUpdateService bookUpdateService;

    // TODO: use an inmemory cache for now but move into the database
    private static final Map<String, Map<Long, KoboEventsContainer.Event>> openEventCache = new HashMap<>();

    private Long getBookId(KoboEventsContainer.Event event) {
        Long bookId = null;
        String monetization = event.getAttributes().getMonetization();
        switch(monetization) {
            case MONETIZATION_TYPE_PAID:
                // ignore ids that are not generated by this application
                if (StringUtils.isNumeric(event.getAttributes().getVolumeid())) {
                    Optional<BookEntity> book = bookRepository.findById(Long.valueOf(event.getAttributes().getVolumeid()));
                    if (book.isEmpty()) {
                        log.warn(String.format("Unable to locate book with id: %s.  Event details: %s", event.getAttributes().getVolumeid(), event.toString()));
                        break;
                    }

                    BookEntity b = book.get();
                    bookId = b.getId();
                }
                break;
            case MONETIZATION_TYPE_SIDELOADED:
                List<BookMetadataEntity> metadata = bookMetadataRepository.findByTitle(event.getAttributes().getTitle());
                if (metadata.isEmpty()) {
                    log.warn(String.format("Unable to locate book named \"%s\".  Event details: %s", event.getAttributes().getTitle(), event.toString()));
                    break;
                }

                bookId = metadata.getFirst().getBookId();
                break;
            default:
                log.warn(String.format("Unknown monetization type: %s.  Event details: ", monetization, event.toString()));
                break;
        }

        return bookId;
    }

    private boolean isDuplicateSession(ReadingSessionEntity session, Instant startTime, Instant endTime) {
        if (startTime == null && session.getStartTime() != null) {
            return false;
        }

        if (startTime != null && !startTime.equals(session.getStartTime())) {
            return false;
        }

        if (endTime == null && session.getEndTime() != null) {
            return false;
        }

        if (endTime != null && !endTime.equals(session.getEndTime())) {
            return false;
        }

        return true;
    }

    private void handleOpenContent(String serial, KoboEventsContainer.Event event) {
        Long bookId = getBookId(event);
        if (bookId == null) {
            return;
        }
        
        // Store the event in cache
        Map<Long, KoboEventsContainer.Event> entry = openEventCache.get(serial);
        if (entry == null) {
            entry = new HashMap<>();
            openEventCache.put(serial, entry);
        }

        if (entry.containsKey(bookId)) {
            log.error(String.format("OpenEvent cache already contains an open event for book id: %d and will be replaced.  Old entry: %s", bookId, entry.get(bookId)));
        }
        entry.put(bookId, event);
    }

    private void handleLeaveContent(String serial, KoboEventsContainer.Event event) {
        Long bookId = getBookId(event);
        if (bookId == null) {
            return;
        }

        // locate the open event in the cache.  Might not exist
        KoboEventsContainer.Event startEvent = null;
        if (openEventCache.containsKey(serial)) {
            startEvent = openEventCache.get(serial).remove(bookId);
        }

        // Ignore events that turn any pages
        if (event.getMetrics().getPagesTurned() == 0) {
            return;
        }

        // Store the reading progress
        BookFileType bookType = BookFileType.EPUB;
        Optional<BookEntity> b = bookRepository.findByIdWithBookFiles(bookId);
        if (b.isPresent()) {
            bookType = b.get().getPrimaryBookFile().getBookType();
        }

        Instant endTime = event.getTimestamp();
        Instant startTime = endTime.minusSeconds(event.getMetrics().getSecondsRead());
        Float startProgress = startEvent == null ? null : startEvent.getAttributes().getProgress(); 
        Float endProgress = event.getAttributes().getProgress();
        Float progressDelta = startProgress == null ? endProgress : (endProgress - startProgress);

        // try to de-duplicate events
        BookLoreUser authenticatedUser = authenticationService.getAuthenticatedUser();
        Long userId = authenticatedUser.getId();
        Page<ReadingSessionEntity> sessions = readingSessionRepository.findByUserIdAndBookId(userId, bookId, Pageable.unpaged());
        for (ReadingSessionEntity session : sessions) {
            if (isDuplicateSession(session, startTime, endTime)) {
                log.info(String.format("Ignoring a duplicate reading session for book id: %d, from %s to %s", bookId, startTime, endTime));
                return;
            }
        }

        ReadingSessionRequest rsr = ReadingSessionRequest.builder()
            .bookId(bookId)
            .bookType(bookType)
            .startTime(startTime)
            .endTime(endTime)
            .durationSeconds(event.getMetrics().getSecondsRead())
            .startProgress(startProgress)
            .endProgress(endProgress)
            .progressDelta(progressDelta)
            .build();

        readingSessionService.recordSession(rsr);
        log.info(String.format("Stored kobo reading event for %d.  From %s to %s.  Pages turned %d.  Progress from %s to %s", bookId, startTime, endTime, event.getMetrics().getPagesTurned(), startProgress, endProgress));
    }

    public void handleEvents(KoboEventsContainer eventsContainer) {
        String serial = eventsContainer.getSerialNumber();
        for (KoboEventsContainer.Event event : eventsContainer.getEvents()) {
            switch(event.getEventType()) {
                case EVENT_TYPE_OPEN_CONTENT:
                    handleOpenContent(serial, event);
                    break;
                case EVENT_TYPE_LEAVE_CONTENT:
                    handleLeaveContent(serial, event);
                    break;
                default:
                    log.debug("Unhandled event type: " + event.getEventType());
                    log.debug("Unhandled event data: " + event.toString());
            }
        }
    }
}
